### ISSUE TITLE
specify how to use

### ISSUE THREAD

**Issue by yannickdoteu** [LudovicLemaire/Slots-finder#1]
Hey Ludovic,

Your project seems interesting! What isn't really clear for me is how I use it. Is there a download for an apk? Do I have to build it myself? Or is it a linux application?

**Comment by LudovicLemaire** [comment]
Hello, you need to download the source code, then edit the api key file to use your own token generated on the intra.

**Comment by LudovicLemaire** [comment]
Hello, you have to download the source code, then edit the api key file to use your own intra token.

Then rebuild it in order to use it.

Saddly I did the app before the api rule change, and it has to be rebuilt every time you change the token. And now, since the token change every months it ain't of best use. It would need an additional page where you put the tokens if previous is invalid. But I haven't done it since the change, and don't know if I ever will.

**Comment by yannickdoteu** [comment]
Okay I understand, thanks a lot !
